from pathlib import Path
p=Path('/mnt/data/weather_upgrade/index.html')
s=p.read_text(encoding='utf-8')
needle='<section id="weather"><div class="wrap"><div class="section-head"><div><div class="kicker">09 · Live weather</div><h2>Weather-ready information layer.</h2></div><div class="location-tools"><button id="useMyLocation" class="btn secondary" type="button">Use my location</button><span id="locationStatus" class="location-status">Using Dhaka fallback until browser location is available.</span></div></div>'
insert='''<section id="weather"><div class="wrap"><div class="section-head"><div><div class="kicker">09 · Live weather</div><h2>Digital 3D atmospheric command view.</h2></div><div class="location-tools"><button id="useMyLocation" class="btn secondary" type="button">Use my location</button><span id="locationStatus" class="location-status">Using Dhaka fallback until browser location is available.</span></div></div><article class="weather-digital-shell card"><div class="weather-digital-head"><div><span class="digital-kicker">DIGITAL ATMOSPHERE ENGINE</span><h3 id="weatherDigitalTitle">LIVE 3D WEATHER</h3><p id="weatherDigitalSub">Depth-rendered atmosphere · forecast stream · environmental telemetry</p></div><div class="weather-digital-status"><span class="weather-live-led"></span><b id="weatherDigitalState">SYNCING</b><small id="weatherDigitalUpdated">--</small></div></div><div class="weather-digital-stage"><canvas id="weather3DDigital" aria-label="Digital 3D weather visualization"></canvas><div class="weather-hud weather-hud-left"><div><span>DIRECT AIR</span><b id="w3Temp">--°</b></div><div><span>HUMIDITY</span><b id="w3Hum">--%</b></div><div><span>WIND</span><b id="w3Wind">--</b></div></div><div class="weather-hud weather-hud-right"><div><span>PRECIP</span><b id="w3Rain">--%</b></div><div><span>CONDITION</span><b id="w3Cond">SYNC</b></div><div><span>VECTOR</span><b id="w3Dir">--</b></div></div><div class="weather-horizon-line"></div><div class="weather-scanline"></div></div><div class="weather-digital-forecast" id="weatherDigitalForecast"></div></article>'''+needle.split('</div>',1)[1]
if needle not in s:
    raise SystemExit('weather section needle not found')
s=s.replace(needle,insert,1)
css=r'''
/* Digital 3D Weather Console */
.weather-digital-shell{margin-top:16px;overflow:hidden;background:linear-gradient(145deg,rgba(5,16,24,.97),rgba(3,9,15,.98));border-color:rgba(85,221,255,.24);box-shadow:0 24px 70px rgba(0,0,0,.28),inset 0 0 60px rgba(85,221,255,.035)}
.weather-digital-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;padding:4px 2px 14px}.digital-kicker{font-size:9px;letter-spacing:.2em;color:#59dbff;text-transform:uppercase}.weather-digital-head h3{margin:4px 0 3px;font-size:25px;letter-spacing:.06em}.weather-digital-head p{margin:0;color:#8da3ae;font-size:11px}.weather-digital-status{min-width:132px;text-align:right}.weather-digital-status b{font-size:10px;letter-spacing:.12em;color:#77f0b5}.weather-digital-status small{display:block;color:#718995;font-size:9px;margin-top:4px}.weather-live-led{display:inline-block;width:8px;height:8px;border-radius:50%;background:#77f0b5;box-shadow:0 0 16px #77f0b5;vertical-align:middle;margin-right:6px}.weather-digital-stage{height:390px;position:relative;border:1px solid rgba(85,221,255,.18);border-radius:18px;overflow:hidden;background:radial-gradient(circle at 50% 36%,rgba(33,117,150,.18),transparent 42%),linear-gradient(180deg,#07131c,#02070b 74%)}.weather-digital-stage canvas{width:100%;height:100%;display:block}.weather-hud{position:absolute;top:14px;display:grid;gap:8px;pointer-events:none}.weather-hud-left{left:14px}.weather-hud-right{right:14px;text-align:right}.weather-hud>div{min-width:100px;padding:7px 9px;border:1px solid rgba(85,221,255,.15);background:rgba(2,11,16,.72);border-radius:10px;backdrop-filter:blur(10px)}.weather-hud span{display:block;font-size:7px;letter-spacing:.16em;color:#69828f}.weather-hud b{display:block;font-size:15px;margin-top:2px}.weather-horizon-line{position:absolute;left:0;right:0;bottom:77px;border-top:1px solid rgba(85,221,255,.13);pointer-events:none}.weather-scanline{position:absolute;inset:0;background:repeating-linear-gradient(180deg,rgba(255,255,255,.018),rgba(255,255,255,.018) 1px,transparent 1px,transparent 5px);mix-blend-mode:screen;pointer-events:none;opacity:.35}.weather-digital-forecast{display:grid;grid-template-columns:repeat(8,minmax(80px,1fr));gap:8px;margin-top:10px;overflow:auto}.weather-digital-forecast>div{padding:8px;border:1px solid rgba(85,221,255,.13);border-radius:10px;background:rgba(5,17,24,.84);min-width:78px}.weather-digital-forecast span{display:block;color:#6f8895;font-size:8px}.weather-digital-forecast b{display:block;margin-top:4px;font-size:13px}.weather-digital-forecast small{display:block;color:#8ba5b0;font-size:8px;margin-top:3px}.weather-digital-forecast strong{display:block;color:#59dbff;font-size:9px;margin-top:4px}.weather{margin-top:16px}
body[data-theme="day"] .weather-digital-shell{background:linear-gradient(145deg,rgba(242,249,252,.96),rgba(231,241,246,.98));box-shadow:0 20px 55px rgba(25,58,70,.10),inset 0 0 50px rgba(0,120,160,.03)}
body[data-theme="day"] .weather-digital-stage{background:linear-gradient(180deg,#d9eef7,#f5fafc 74%)}
body[data-theme="day"] .weather-hud>div,body[data-theme="day"] .weather-digital-forecast>div{background:rgba(246,252,255,.78);border-color:rgba(0,105,140,.12)}
@media(max-width:800px){.weather-digital-stage{height:350px}.weather-digital-head{display:block}.weather-digital-status{text-align:left;margin-top:8px}.weather-digital-forecast{grid-template-columns:repeat(8,85px)}.weather-hud>div{min-width:86px}.weather-hud b{font-size:13px}}
'''
# inject before closing head
s=s.replace('</head>', '<style>'+css+'</style></head>',1)
js=r'''
/* Digital 3D weather engine: additive, data-driven, no replacement of existing weather API. */
(function(){
  const canvas=document.getElementById('weather3DDigital'); if(!canvas) return;
  const ctx=canvas.getContext('2d'); if(!ctx) return;
  const $=id=>document.getElementById(id);
  const state={temp:null,hum:null,wind:null,rain:null,cond:'SYNC',dir:'--',code:null,particles:[],stars:[],phase:0,clouds:[],w:0,h:0,d:1};
  function resize(){const r=canvas.getBoundingClientRect();state.d=Math.min(2,window.devicePixelRatio||1);state.w=Math.max(320,r.width);state.h=Math.max(260,r.height);canvas.width=Math.round(state.w*state.d);canvas.height=Math.round(state.h*state.d);canvas.style.width=state.w+'px';canvas.style.height=state.h+'px';ctx.setTransform(state.d,0,0,state.d,0,0);}
  function getTheme(){return document.body?.dataset.theme||'night';}
  function cssVar(name, fallback){const v=getComputedStyle(document.body).getPropertyValue(name).trim();return v||fallback;}
  function weatherCode(){const t=$('weatherText')?.textContent?.trim()||''; const ico=$('weatherIcon')?.textContent?.trim()||''; return {text:t,icon:ico};}
  function sync(){
    const tempTxt=$('temp')?.textContent||''; const humTxt=$('humidity')?.textContent||''; const windTxt=$('wind')?.textContent||''; const rainTxt=$('rainProb')?.textContent||'';
    state.temp=parseFloat(tempTxt); state.hum=parseFloat(humTxt); state.wind=parseFloat(windTxt); state.rain=parseFloat(rainTxt); state.cond=weatherCode().text||'SYNC';
    const dir=$('windDir')?.textContent||''; const m=dir.match(/(\d+)°/); state.dir=m?m[1]+'°':'--';
    $('w3Temp').textContent=Number.isFinite(state.temp)?Math.round(state.temp)+'°':'--°'; $('w3Hum').textContent=Number.isFinite(state.hum)?Math.round(state.hum)+'%':'--%'; $('w3Wind').textContent=Number.isFinite(state.wind)?Math.round(state.wind)+' km/h':'--'; $('w3Rain').textContent=Number.isFinite(state.rain)?Math.round(state.rain)+'%':'--%'; $('w3Cond').textContent=state.cond.toUpperCase().slice(0,15); $('w3Dir').textContent=state.dir;
    const live=$('weatherLiveIndicator')?.textContent||''; $('weatherDigitalState').textContent=live.replace('WEATHER ','').trim()||'SYNCING'; $('weatherDigitalUpdated').textContent=$('weatherUpdated')?.textContent||'--';
    const box=$('weatherDigitalForecast'); const src=$('weatherHourly'); if(box&&src){const cards=[...src.querySelectorAll('.weather-hour')].slice(0,8); if(cards.length){box.innerHTML=cards.map(c=>c.outerHTML).join('');}}
  }
  function seed(){state.clouds=Array.from({length:16},(_,i)=>({x:(i/16)*state.w*1.2-40,y:70+((i*37)%120),z:.35+((i*19)%65)/100,s:28+((i*11)%50)}));state.stars=Array.from({length:65},(_,i)=>({x:(i*47)%Math.max(1,state.w),y:(i*83)%Math.max(1,state.h*.55),a:.18+((i*13)%65)/100}));state.particles=[];for(let i=0;i<130;i++)state.particles.push({x:Math.random(),y:Math.random(),z:Math.random(),vx:0,vy:.006+.018*Math.random()});}
  function sky(){const night=getTheme()==='night';const g=ctx.createLinearGradient(0,0,0,state.h);if(night){g.addColorStop(0,'#02070f');g.addColorStop(.55,'#071721');g.addColorStop(1,'#031017')}else{g.addColorStop(0,'#8fd9ff');g.addColorStop(.55,'#d8f2fc');g.addColorStop(1,'#eff9fb')}ctx.fillStyle=g;ctx.fillRect(0,0,state.w,state.h);}
  function drawStars(){if(getTheme()!=='night')return;ctx.fillStyle='#b9efff';state.stars.forEach(s=>{ctx.globalAlpha=s.a*(.65+.35*Math.sin(state.phase*.02+s.x));ctx.fillRect(s.x,s.y,1.2,1.2)});ctx.globalAlpha=1;}
  function drawSun(){const night=getTheme()==='night';const cx=state.w*.78,cy=state.h*.22,r=night?29:34;const grad=ctx.createRadialGradient(cx,cy,0,cx,cy,r*2.2);grad.addColorStop(0,night?'rgba(194,223,255,.95)':'rgba(255,245,166,.95)');grad.addColorStop(.2,night?'rgba(132,194,255,.48)':'rgba(255,194,82,.48)');grad.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(cx,cy,r*2.2,0,Math.PI*2);ctx.fill();ctx.fillStyle=night?'#d4e8ff':'#ffe79a';ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();}
  function drawHorizon(){const y=state.h*.78;const g=ctx.createLinearGradient(0,y,0,state.h);g.addColorStop(0,'rgba(31,124,153,.18)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,y,state.w,state.h-y);ctx.strokeStyle='rgba(92,222,255,.14)';ctx.lineWidth=1;for(let i=0;i<10;i++){const yy=y+Math.pow(i/9,1.6)*(state.h-y);ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(state.w,yy);ctx.stroke();}for(let i=-8;i<=8;i++){ctx.beginPath();ctx.moveTo(state.w/2+i*20,y);ctx.lineTo(state.w/2+i*55,state.h);ctx.stroke();}}
  function drawCloud(c){const wob=Math.sin(state.phase*.015+c.x*.01)*3;const x=((c.x+state.phase*c.z*.06)%(state.w+160))-80;const y=c.y+wob;const s=c.s*(.8+c.z*.35);const grd=ctx.createRadialGradient(x,y,0,x,y,s*1.8);grd.addColorStop(0,getTheme()==='night'?'rgba(178,220,238,.16)':'rgba(255,255,255,.75)');grd.addColorStop(1,'rgba(120,170,190,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.ellipse(x,y,s*1.45,s*.52,0,0,Math.PI*2);ctx.fill();}
  function drawClouds(){state.clouds.forEach(drawCloud);}
  function drawRain(){const rain=(Number.isFinite(state.rain)?state.rain:0);const active=rain>20 || /rain|showers|drizzle|thunder/i.test(state.cond);if(!active)return;ctx.strokeStyle='rgba(121,214,255,.35)';ctx.lineWidth=1;const speed=.008+Math.min(Math.max(Number(state.wind)||0,0),80)*.00014;state.particles.forEach(p=>{p.x+=.0009+(Number(state.wind)||0)*.000002;p.y+=speed;p.x%=1;if(p.y>1){p.y=-.05;p.x=Math.random();}const x=p.x*state.w,y=p.y*state.h*.72;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-6,y+16);ctx.stroke();});}
  function drawWind(){const speed=Math.min(Math.max(Number(state.wind)||0,0),100);ctx.strokeStyle='rgba(113,241,255,.18)';ctx.lineWidth=1;for(let i=0;i<10;i++){const yy=120+i*24;const bend=Math.sin(state.phase*.018+i)*10;ctx.beginPath();ctx.moveTo(40,yy);ctx.bezierCurveTo(state.w*.32,yy+bend,state.w*.66,yy-bend,state.w-40,yy+Math.sin(state.phase*.02+i)*5);ctx.stroke();}ctx.fillStyle='rgba(117,241,255,.65)';ctx.font='10px system-ui';ctx.fillText('WIND VECTOR '+(Number.isFinite(state.wind)?Math.round(state.wind)+' km/h':'--'),state.w*.5-65,state.h-24);}
  function frame(){sky();drawStars();drawSun();drawClouds();drawRain();drawWind();drawHorizon();state.phase++;requestAnimationFrame(frame);}
  resize();seed();sync();frame();window.addEventListener('resize',()=>{resize();seed()});
  const obs=new MutationObserver(()=>sync());['temp','humidity','wind','rainProb','weatherText','weatherUpdated','weatherHourly','weatherLiveIndicator','windDir'].forEach(id=>{const el=$(id);if(el)obs.observe(el,{childList:true,subtree:true,characterData:true,attributes:true})});
  setInterval(sync,2500);
})();
'''
# append before closing body
s=s.replace('</body>', '<script>'+js+'</script></body>',1)
p.write_text(s,encoding='utf-8')
print('patched',p)
