/* IGERS-BD-01 — Next-Gen Engineering Simulation & Conceptual 3D Command Center
   Additive module: preserves the legacy application and owns its own state, panels and calculations. */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=(v,d=2)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const models={
  road:{name:'Road Kinetic Recovery',short:'ROAD · CONTROLLED RECOVERY',desc:'Controlled deceleration / compression energy model',eq:'E_event = 1/2 m(v₁²−v₂²) × η',inputs:[['mass','Vehicle mass','kg',900],['v1','Entry speed','km/h',20],['v2','Exit speed','km/h',15],['eta','Electrical chain efficiency','%',70],['events','Vehicle events / day / point','events/day',1000],['points','Active recovery points','points',1]],calc:v=>{const m=Math.max(0,v.mass),a=Math.max(0,v.v1)/3.6,b=Math.max(0,v.v2)/3.6,eta=Math.min(1,Math.max(0,v.eta)/100),e=Math.max(0,v.events),p=Math.max(1,v.points);const j=.5*m*Math.max(0,a*a-b*b),wh=j/3600*eta,yk=wh*e*p*365/1000;return {cards:[['EVENT ENERGY',fmt(wh,3)+' Wh'],['ANNUAL',fmt(yk/1000,3)+' MWh'],['AVG POWER',fmt(yk/8760,2)+' kW'],['EVENTS',Math.round(e*p).toLocaleString()+'/day']],equation:`${models.road.eq} · ΔE=${fmt(j,1)} J/event · usable=${fmt(wh,3)} Wh/event`,annualMWh:yk}}},
  water:{name:'River Current Hydrokinetic',short:'WATER · FREE STREAM',desc:'Current-based turbine model',eq:'P = 0.5ρAv³Cₚη',inputs:[['rho','Water density','kg/m³',1000],['area','Swept area','m²',50],['speed','Current speed','m/s',1.5],['cp','Power coefficient','%',35],['eta','Generator chain','%',90],['cf','Capacity factor','%',50]],calc:v=>{const p=.5*v.rho*v.area*Math.pow(Math.max(0,v.speed),3)*(v.cp/100)*(v.eta/100);const yk=p*(v.cf/100)*8760/1000;return {cards:[['RATED POWER',fmt(p/1000,2)+' kW'],['ANNUAL',fmt(yk/1000,2)+' MWh'],['AVERAGE',fmt(p*(v.cf/100)/1000,2)+' kW'],['FLOW SPEED',fmt(v.speed,2)+' m/s']],equation:`${models.water.eq} · rated=${fmt(p,0)} W`,annualMWh:yk/1000}}},
  hydraulic:{name:'Regulator / Low-Head Hydraulic',short:'WATER · HEAD RECOVERY',desc:'Controlled-flow turbine in a protected bypass or outlet',eq:'P = ρgQHη',inputs:[['rho','Water density','kg/m³',1000],['flow','Flow Q','m³/s',5],['head','Head H','m',1.5],['eta','Overall efficiency','%',70],['cf','Annual availability','%',40],['units','Parallel units','units',1]],calc:v=>{const p=v.rho*9.81*Math.max(0,v.flow)*Math.max(0,v.head)*(v.eta/100);const yk=p*(v.cf/100)*8760*Math.max(1,v.units)/1000;return {cards:[['RATED POWER',fmt(p/1000,2)+' kW'],['ANNUAL',fmt(yk/1000,2)+' MWh'],['AVG FLEET',fmt(yk/8760,2)+' kW'],['UNITS',Math.max(1,Math.round(v.units)).toLocaleString()]],equation:`${models.hydraulic.eq} · fleet annual=${fmt(yk/1000,2)} MWh`,annualMWh:yk/1000}}},
  footstep:{name:'Footstep / Pedestrian Micro-Harvest',short:'PEDESTRIAN · MICRO POWER',desc:'High-footfall auxiliary energy model',eq:'E_year = steps/day × J/step × η × 365',inputs:[['steps','Steps / day','steps/day',100000],['joule','Energy captured / step','J/step',2],['eta','Electrical efficiency','%',100],['points','Pad clusters','clusters',1]],calc:v=>{const wh=v.steps*v.joule*(v.eta/100)/3600,yk=wh*365*Math.max(1,v.points)/1000;return {cards:[['DAILY',fmt(wh/1000,3)+' kWh'],['ANNUAL',fmt(yk,2)+' kWh'],['AVG POWER',fmt(yk/8760,3)+' kW'],['USE CLASS','AUXILIARY']],equation:`${models.footstep.eq} · sensor / LED / IoT role`,annualMWh:yk/1000}}},
  bridge:{name:'Bridge / Culvert Energy Node',short:'BRIDGE · CONTROLLED BYPASS',desc:'Protected bridge/culvert head-difference module',eq:'P = ρgQHη',inputs:[['flow','Available flow Q','m³/s',2],['head','Local drop H','m',1],['eta','Overall efficiency','%',65],['cf','Availability','%',30],['units','Node count','nodes',1],['rho','Water density','kg/m³',1000]],calc:v=>{const p=v.rho*9.81*v.flow*v.head*(v.eta/100),yk=p*(v.cf/100)*8760*v.units/1000;return {cards:[['NODE POWER',fmt(p/1000,2)+' kW'],['ANNUAL',fmt(yk/1000,2)+' MWh'],['AVG OUTPUT',fmt(yk/8760,2)+' kW'],['NODES',Math.max(1,Math.round(v.units)).toLocaleString()]],equation:`${models.bridge.eq} · primary structure remains independent`,annualMWh:yk/1000}}},
  rail:{name:'Rail Regenerative Braking',short:'RAIL · REGEN BRAKING',desc:'Train deceleration and wayside storage screening model',eq:'E = 1/2mv² × η × stops/day',inputs:[['mass','Train mass','tonnes',200],['speed','Braking speed','km/h',40],['eta','Recovery fraction','%',65],['stops','Meaningful stops / train / day','stops',1],['trains','Trains / day','trains/day',20]],calc:v=>{const j=.5*(v.mass*1000)*Math.pow(v.speed/3.6,2),kwh=j/3.6e6*(v.eta/100),yk=kwh*v.stops*v.trains*365;return {cards:[['PER STOP',fmt(kwh,2)+' kWh'],['ANNUAL',fmt(yk/1000,3)+' MWh'],['AVG POWER',fmt(yk/8760,2)+' kW'],['TRAIN DAYS',Math.round(v.trains*365).toLocaleString()]],equation:`${models.rail.eq} · ${fmt(j/1e6,2)} MJ kinetic ceiling/stop`,annualMWh:yk/1000}}},
  airport:{name:'Airport PV Canopy + Footstep',short:'AIRPORT · PV-FIRST',desc:'PV-first resilient airport canopy with micro-harvest support',eq:'E_PV = MWp × 1000 × specific yield',inputs:[['mw','PV capacity','MWp',1],['yield','PV specific yield','kWh/kWp-y',1400],['steps','Footsteps/day','steps/day',50000],['joule','Captured energy/step','J/step',1],['eta','Footstep efficiency','%',80],['cf','PV utilization factor','%',100]],calc:v=>{const pv=v.mw*1000*v.yield*(v.cf/100),foot=v.steps*v.joule*(v.eta/100)/3600*365/1000;return {cards:[['PV',fmt(pv/1000,2)+' MWh/y'],['FOOTSTEP',fmt(foot,2)+' kWh/y'],['TOTAL',fmt(pv/1000+foot/1000,2)+' MWh/y'],['PRIMARY','PV-FIRST']],equation:`${models.airport.eq} · runway-surface harvesting excluded from base case`,annualMWh:pv/1000+foot/1000}}},
  hybrid:{name:'Hybrid Solar + VAWT Resilience Node',short:'HYBRID · PV + VAWT',desc:'Distributed solar and wind-support node with local storage',eq:'P_wind = 0.5ρAv³Cₚη',inputs:[['mw','PV capacity','MWp',0.4],['yield','PV specific yield','kWh/kWp-y',1400],['area','Wind swept area','m²',20],['speed','Wind speed','m/s',5],['cp','Wind Cp','%',30],['eta','Wind chain','%',80]],calc:v=>{const pv=v.mw*1000*v.yield,wind=.5*1.225*v.area*Math.pow(v.speed,3)*(v.cp/100)*(v.eta/100)*8760/1000;return {cards:[['PV',fmt(pv/1000,2)+' MWh/y'],['WIND',fmt(wind/1000,2)+' MWh/y'],['TOTAL',fmt((pv+wind)/1000,2)+' MWh/y'],['NODE','RESILIENCE']],equation:`${models.hybrid.eq} + PV benchmark · wind CF must be validated`,annualMWh:(pv+wind)/1000}}},
  bess:{name:'BESS + Local Load Sizing',short:'BESS · STORAGE',desc:'First-pass storage sizing from daily load and duration',eq:'E_BESS = daily load × duration / 24 ÷ DoD ÷ RTE',inputs:[['daily','Daily load','MWh/day',30],['hours','Autonomy duration','hours',6],['dod','Depth of discharge','%',80],['rte','Round-trip efficiency','%',90],['power','Peak power','MW',5]],calc:v=>{const usable=v.daily*(v.hours/24),cap=usable/((v.dod/100)*(v.rte/100));return {cards:[['USABLE ENERGY',fmt(usable,2)+' MWh'],['BESS NOMINAL',fmt(cap,2)+' MWh'],['PEAK POWER',fmt(v.power,2)+' MW'],['DURATION',fmt(cap/Math.max(.01,v.power),2)+' h']],equation:`${models.bess.eq} · conceptual first-pass; final sizing needs load profile, BMS and thermal design`,annualMWh:0}}}
};
const defaultState={model:'road',run:true,rotate:true,grid:true,intensity:1};
let state=loadState();
function loadState(){try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem('igersNextGenStateV1')||'{}'))}catch(_){return {...defaultState}}}
function saveState(){try{localStorage.setItem('igersNextGenStateV1',JSON.stringify(state))}catch(_){} }
function inject(){
  if($('engineeringLab'))return;
  const target=$('feedback')||$('inventor')||document.querySelector('main'); if(!target)return;
  const nav=document.querySelector('.navlinks'); const navGroup=nav?.querySelector('[data-nav-group="engineering"]')||nav; if(navGroup&&!navGroup.querySelector('a[href="#engineeringLab"]')){const a=document.createElement('a');a.href='#engineeringLab';a.textContent='Simulation Lab';navGroup.appendChild(a)}
  const section=document.createElement('section'); section.id='engineeringLab'; section.innerHTML=`<div class="wrap nx-shell">
    <div class="nx-command">
      <article class="nx-panel">
        <div class="nx-head"><div><div class="nx-kicker">13 · Engineering Simulation Command Center</div><div class="nx-title">IGERS-BD-01 · Conceptual 3D Model + Automatic Calculation System</div><div class="nx-sub">Every model is isolated in its own panel. Inputs drive the simulation automatically; conceptual output never replaces field measurement.</div></div><div class="nx-badges"><span id="nxLive" class="nx-badge"><i class="led"></i>SIMULATION LIVE</span><span class="nx-badge">LOCAL ENGINE</span></div></div>
        <div class="nx-navrail"><button class="nx-navbtn active" data-jump="#nxModels">MODEL GALLERY</button><button class="nx-navbtn" data-jump="#nxCalc">CALCULATION</button><button class="nx-navbtn" data-jump="#nxArchitecture">ARCHITECTURE</button><button class="nx-navbtn" data-jump="#nxFleet">FLEET SUMMARY</button><button class="nx-navbtn" data-jump="#nxAdmin">CONTROL</button></div>
      </article>
      <article class="nx-panel"><div class="nx-head"><div><div class="nx-kicker">SYSTEM STATE</div><div class="nx-title">Runtime monitor</div></div><span id="nxModelBadge" class="nx-badge">ROAD</span></div><div class="nx-stats"><div class="nx-stat"><b id="nxHeartbeat">1.0 s</b><span>Engine tick</span></div><div class="nx-stat"><b id="nxRenderState">3D ON</b><span>Renderer</span></div><div class="nx-stat"><b id="nxSelectedValue">0.000</b><span>Selected annual MWh</span></div><div class="nx-stat"><b id="nxClock">--:--:--</b><span>Local sync</span></div></div></article>
    </div>
    <div id="nxModels" class="nx-model-layout">
      <article class="nx-panel"><div class="nx-head"><div><div class="nx-kicker">03D MODEL GALLERY</div><div class="nx-title">Select a conceptual model</div><div class="nx-sub">Road · water · bridge · rail · airport · hybrid · BESS</div></div></div><div class="nx-model-grid" id="nxModelGrid"></div></article>
      <article class="nx-panel nx-view"><div class="nx-head"><div><div class="nx-kicker" id="nxModelKicker">ACTIVE MODEL</div><div class="nx-title" id="nxModelTitle">Road Kinetic Recovery</div><div class="nx-sub" id="nxModelDesc">Controlled deceleration / compression energy model</div></div><div class="nx-badges"><span class="nx-badge"><i class="led"></i>3D SIM</span><span class="nx-badge" id="nxFrameRate">60 FPS TARGET</span></div></div><div class="nx-viewport"><canvas id="nx3dCanvas" aria-label="IGERS conceptual 3D engineering simulation"></canvas><div class="nx-crosshair"></div><div class="nx-model-overlay"><div class="nx-overlay-name" id="nxOverlayName">ROAD RECOVERY MODULE</div><div class="nx-overlay-state" id="nxOverlayState">PARAMETRIC / CONCEPTUAL / NON-CONSTRUCTION</div></div></div><div class="nx-badges"><span class="nx-badge">Drag-ready camera architecture</span><span class="nx-badge">Auto rotate <b id="nxRotateLabel">ON</b></span><span class="nx-badge">Grid <b id="nxGridLabel">ON</b></span></div></article>
    </div>
    <div id="nxCalc" class="nx-calc-layout">
      <article class="nx-panel" id="energyLiveUpdate"><div class="nx-head"><div><div class="nx-kicker">AUTOMATIC CALCULATION PANEL</div><div class="nx-title" id="nxCalcTitle">Road Kinetic Recovery</div><div class="nx-sub">Change any input and results recalculate immediately.</div></div><span id="energyLiveBadge" class="nx-badge"><i class="led"></i>LIVE CALCULATION</span></div><div class="nx-input-grid" id="nxInputGrid"></div><div class="nx-results" id="nxResults"></div><div class="nx-equation" id="nxEquation">Equation loading…</div><div id="energyEngineState" class="nx-note" style="margin-top:8px">ENGINE ACTIVE · REAL-TIME MODEL</div></article>
      <article class="nx-panel"><div class="nx-head"><div><div class="nx-kicker">MODEL DECISION PANEL</div><div class="nx-title">What the output means</div></div><span id="sysEnergyState" class="nx-badge">ON · CALCULATOR</span></div><div class="nx-list" id="nxDecisionList"></div><div class="nx-note" style="margin-top:10px">Classification is intentionally conservative: conceptual, scenario-based and site-dependent modules stay visibly separate from measured live data.</div></article>
    </div>
    <div id="nxArchitecture" class="nx-panel"><div class="nx-head"><div><div class="nx-kicker">SYSTEM ARCHITECTURE</div><div class="nx-title">Source → Recovery → Conditioning → BESS → Local Load → Monitor</div></div><span class="nx-badge">UNIFIED BACKBONE</span></div><div class="nx-architecture"><div class="nx-stage">SOURCE<br>ROAD / SUN / WATER / HUMAN</div><div class="nx-arrow">→</div><div class="nx-stage">RECOVERY<br>MECHANISM</div><div class="nx-arrow">→</div><div class="nx-stage">POWER<br>CONDITIONING</div><div class="nx-arrow">→</div><div class="nx-stage">BESS<br>+ PROTECTION</div></div><div class="nx-architecture" style="margin-top:8px"><div class="nx-stage">LOCAL<br>LIGHTING / IoT</div><div class="nx-arrow">←</div><div class="nx-stage">MONITOR / TELEMETRY</div><div class="nx-arrow">←</div><div class="nx-stage">MAINTENANCE<br>+ BYPASS</div><div class="nx-arrow">←</div><div class="nx-stage">GRID / BACKUP<br>OPTIONAL</div></div></div>
    <div id="nxFleet" class="nx-panel"><div class="nx-head"><div><div class="nx-kicker">FLEET SUMMARY</div><div class="nx-title">Scenario outputs across the conceptual portfolio</div></div><span class="nx-badge">AUTO REFRESH</span></div><div class="nx-list" id="nxFleetList"></div></div>
    <div id="nxAdmin" class="nx-panel"><div class="nx-head"><div><div class="nx-kicker">SIMULATION CONTROL</div><div class="nx-title">Administrative 3D &amp; calculation controls</div><div class="nx-sub">Local browser control only. GitHub Pages cannot provide a secure server-side password boundary.</div></div><span id="nxAdminState" class="nx-badge warn">LOCKED</span></div><div class="nx-admin"><div class="nx-admin-actions"><button class="nx-action primary" id="nxAdminLogin" type="button">UNLOCK WITH LOCAL ADMIN KEY</button><button class="nx-action" id="nxRunToggle" type="button">STOP SIMULATION</button><button class="nx-action" id="nxRotateToggle" type="button">TOGGLE 3D ROTATION</button><button class="nx-action" id="nxGridToggle" type="button">TOGGLE GRID</button><button class="nx-action" id="nxReset" type="button">RESET MODEL INPUTS</button></div><div class="nx-note" id="nxAdminNote">Default local demo key: IGERS-2026. Change it through the local browser prompt after unlocking. This is a client-side simulation control, not production authentication.</div></div></div>
    <button class="nx-scroll-top" id="nxTop" type="button" aria-label="Back to top">↑</button>
  </div>`;
  target.parentNode.insertBefore(section,target);
}
function modelButtonHtml(key,m){return `<button class="nx-modelbtn${state.model===key?' active':''}" data-model="${key}"><b>${esc(m.name)}</b><span>${esc(m.desc)}</span></button>`}
function renderModelGallery(){const box=$('nxModelGrid');if(!box)return;box.innerHTML=Object.entries(models).map(([k,m])=>modelButtonHtml(k,m)).join('');box.querySelectorAll('[data-model]').forEach(b=>b.addEventListener('click',()=>{state.model=b.dataset.model;saveState();renderAll()}))}
function readInputs(){const m=models[state.model];const out={};m.inputs.forEach(([id,,unit,def])=>{const el=$('nx_'+id);const n=Number(el?.value);out[id]=Number.isFinite(n)?n:def});return out}
function renderInputs(){const m=models[state.model],box=$('nxInputGrid');if(!box)return;box.innerHTML=m.inputs.map(([id,label,unit,def])=>`<div class="nx-field"><label for="nx_${id}">${esc(label)} · ${esc(unit)}</label><input id="nx_${id}" type="number" step="any" inputmode="decimal" value="${def}"></div>`).join('');box.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{saveInputSnapshot();calculateCurrent()}));restoreInputSnapshot()}
function keyForInput(){return 'igersNextGenInputsV1_'+state.model}
function saveInputSnapshot(){const m=models[state.model],o={};m.inputs.forEach(([id])=>{o[id]=$('nx_'+id)?.value});try{localStorage.setItem(keyForInput(),JSON.stringify(o))}catch(_){} }
function restoreInputSnapshot(){try{const o=JSON.parse(localStorage.getItem(keyForInput())||'{}');Object.entries(o).forEach(([id,v])=>{const e=$('nx_'+id);if(e&&v!==undefined)e.value=v})}catch(_){} }
function decisionRows(m,res){const good=res.annualMWh>0;const rows=[['MODEL STATUS',good?'CALCULATABLE':'STORAGE SIZING MODE',good?'Live local simulation':'Conceptual parameter model'],['EVIDENCE TIER',state.model==='airport'||state.model==='bess'?'MATURE + SITE-CONSTRAINED':'SITE / RESOURCE DEPENDENT','Field measurements still required'],['SAFETY GATE','REQUIRED','No result authorizes construction'],['ENERGY ACCOUNTING',state.model==='footstep'?'MICRO-POWER':'BOUNDARY OUTPUT','Do not double-count source energy']];return rows.map(r=>`<div class="nx-row"><div><b>${esc(r[0])}</b><small>${esc(r[2])}</small></div><strong>${esc(r[1])}</strong></div>`).join('')}
function renderFleet(){const box=$('nxFleetList');if(!box)return;let total=0;const rows=Object.entries(models).filter(([k])=>k!=='bess').map(([k,m])=>{let res;try{const vals={};m.inputs.forEach(([id,,u,d])=>vals[id]=d);res=m.calc(vals)}catch(_){res={annualMWh:0,cards:[]}}total+=res.annualMWh||0;const active=k===state.model?' · ACTIVE':'';return `<div class="nx-row"><div><b>${esc(m.short+active)}</b><small>${esc(m.name)}</small></div><strong>${fmt(res.annualMWh||0,3)} MWh/y</strong></div>`}).join('');box.innerHTML=rows+`<div class="nx-row" style="margin-top:4px;border-color:#2a6272;background:#08202a"><div><b>PORTFOLIO SCREENING SUM</b><small>Independent scenario models; not a combined guaranteed yield.</small></div><strong>${fmt(total,3)} MWh/y</strong></div>`}
function calculateCurrent(){const m=models[state.model];const vals=readInputs();const res=m.calc(vals);$('nxCalcTitle').textContent=m.name;$('nxModelTitle').textContent=m.name;$('nxModelDesc').textContent=m.desc;$('nxModelBadge').textContent=state.model.toUpperCase();$('nxOverlayName').textContent=m.short;$('nxSelectedValue').textContent=fmt(res.annualMWh||0,3);$('nxEquation').textContent=res.equation;$('nxResults').innerHTML=res.cards.map(c=>`<div class="nx-result"><strong>${esc(c[1])}</strong><span>${esc(c[0])}</span></div>`).join('');$('nxDecisionList').innerHTML=decisionRows(m,res);const led=$('energyLiveBadge');if(led){led.className='nx-badge';led.innerHTML='<i class="led"></i>LIVE CALCULATION'}$('energyEngineState').textContent='ENGINE ACTIVE · REAL-TIME MODEL';if($('sysEnergyState'))$('sysEnergyState').textContent='ON · CALCULATOR';renderFleet();draw3D()}
function project(x,y,z,cx,cy,s,rx,ry){let X=x,Y=y,Z=z;let cy0=Math.cos(rx),sy0=Math.sin(rx),cx0=Math.cos(ry),sx0=Math.sin(ry);let y1=Y*cy0-Z*sy0,z1=Y*sy0+Z*cy0,x1=X*cx0-z1*sx0,z2=X*sx0+z1*cx0;const p=1/(1+z2*.0018);return [cx+x1*s*p,cy-y1*s*p]}
let angle=0;
function draw3D(){const c=$('nx3dCanvas');if(!c)return;const dpr=window.devicePixelRatio||1,w=c.clientWidth||800,h=c.clientHeight||390;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const p=state.intensity;const cx=w/2,cy=h/2+20,s=Math.min(w,h)*.18;
  if(state.grid){ctx.lineWidth=1;ctx.strokeStyle='rgba(88,221,255,.09)';for(let i=-5;i<=5;i++){let a=project(i*7,-40,-20,cx,cy,s,.22,angle);let b=project(i*7,-40,40,cx,cy,s,.22,angle);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();let c1=project(-40,-40,i*7,cx,cy,s,.22,angle);let c2=project(40,-40,i*7,cx,cy,s,.22,angle);ctx.beginPath();ctx.moveTo(...c1);ctx.lineTo(...c2);ctx.stroke()}}
  const line=(pts,col='rgba(88,221,255,.72)',lw=1.6)=>{ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.beginPath();pts.forEach((q,i)=>{const P=project(q[0],q[1],q[2],cx,cy,s,.22,angle);i?ctx.lineTo(...P):ctx.moveTo(...P)});ctx.stroke()};
  const fillPoly=(pts,fill='rgba(88,221,255,.08)',stroke='rgba(88,221,255,.58)')=>{ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.beginPath();pts.forEach((q,i)=>{const P=project(q[0],q[1],q[2],cx,cy,s,.22,angle);i?ctx.lineTo(...P):ctx.moveTo(...P)});ctx.closePath();ctx.fill();ctx.stroke()};
  const box=(x1,x2,y1,y2,z1,z2)=>{const faces=[[[x1,y1,z1],[x2,y1,z1],[x2,y2,z1],[x1,y2,z1]],[[x1,y1,z2],[x2,y1,z2],[x2,y2,z2],[x1,y2,z2]],[[x1,y1,z1],[x1,y1,z2],[x1,y2,z2],[x1,y2,z1]],[[x2,y1,z1],[x2,y1,z2],[x2,y2,z2],[x2,y2,z1]],[[x1,y2,z1],[x2,y2,z1],[x2,y2,z2],[x1,y2,z2]]];faces.forEach((f,i)=>fillPoly(f,i===4?'rgba(121,243,181,.12)':'rgba(88,221,255,.07)'))};
  const label=(t,x,y)=>{ctx.fillStyle='#bdefff';ctx.font='700 11px system-ui';ctx.fillText(t,x,y)};
  switch(state.model){
    case 'road': box(-46,46,-3,3,-20,20); line([[-42,4,-18],[42,4,-18]],'rgba(121,243,181,.55)',1.2); for(let x=-28;x<=28;x+=14){line([[x,-10,-16],[x+5,-10,16]],'rgba(255,210,122,.35)',1)} box(-12,12,3,10,-12,12); box(-8,8,10,14,-7,7); label('CONTROLLED RECOVERY MODULE',cx-84,34); break;
    case 'water': box(-36,0,-3,3,-22,22); for(let z=-18;z<=18;z+=6)line([[-25,6,z],[-4,6,z+2],[18,6,z]],'rgba(95,170,255,.42)',1); for(let i=0;i<5;i++){const x=-4+i*6;line([[x,0,-8],[x,8,-4],[x,0,8],[x,-8,4],[x,0,-8]],'rgba(121,243,181,.7)',1.4)} box(4,22,-1,10,-12,12); label('HYDROKINETIC TURBINE',cx-70,34); break;
    case 'hydraulic': box(-34,34,-14,20,-20,20); box(-16,16,20,31,-12,12); for(let z=-9;z<=9;z+=6)line([[-16,10,z],[16,10,z]],'rgba(95,170,255,.5)',1); box(-8,8,6,13,-7,7); label('REGULATOR / BYPASS',cx-58,34); break;
    case 'footstep': box(-34,34,-4,2,-20,20); for(let x=-24;x<=24;x+=12){box(x-3,x+3,2,6,-10,10);line([[x,6,-10],[x,10,10]],'rgba(121,243,181,.7)',1.4)} label('FOOTSTEP PAD ARRAY',cx-60,34); break;
    case 'bridge': box(-45,45,0,4,-15,15); for(let x=-30;x<=30;x+=30){box(x-2,x+2,4,35,-2,2)} line([[-38,35,0],[0,15,0],[38,35,0]],'rgba(121,243,181,.75)',1.8); box(-5,4,4,14,-5,5); label('BRIDGE / CULVERT NODE',cx-70,34); break;
    case 'rail': box(-45,5,-2,2,-18,18);box(-45,4,2,5,-18,18);box(-18,20,-8,0,-10,10); line([[-42,8,-14],[-42,8,14]],'rgba(121,243,181,.75)',1.2); for(let x=-36;x<=0;x+=9)line([[x,0,-13],[x,0,13]],'rgba(255,210,122,.38)',1); label('REGENERATIVE RAIL NODE',cx-68,34); break;
    case 'airport': box(-42,42,-2,2,-20,20); for(let x=-30;x<=30;x+=15){fillPoly([[x,-2,-15],[x+6,-2,-7],[x+6,-2,7],[x,-2,15],[x-6,-2,7],[x-6,-2,-7]],'rgba(88,221,255,.12)','rgba(88,221,255,.58)')} box(-8,8,2,10,-6,6); label('PV CANOPY + MICRO-HARVEST',cx-82,34); break;
    case 'hybrid': box(-32,0,-5,0,-18,18); for(let z=-12;z<=12;z+=6)line([[-24,1,z],[0,1,z+2],[24,1,z]],'rgba(255,210,122,.42)',1); for(let i=0;i<5;i++){const ang=angle+i*1.25;const x=18+Math.cos(ang)*8,z=Math.sin(ang)*8;line([[18,8,0],[x,8,z]],'rgba(121,243,181,.78)',1.6)} box(10,26,-1,10,-10,10); label('HYBRID PV + VAWT NODE',cx-72,34); break;
    case 'bess': box(-20,20,-18,14,-10,10); for(let x=-14;x<=14;x+=7){box(x-2,x+2,14,23,-6,6);line([[x,23,-5],[x,28,5]],'rgba(121,243,181,.75)',1.4)} line([[-40,8,0],[-20,8,0]],'rgba(255,210,122,.75)',2); line([[20,8,0],[40,8,0]],'rgba(88,221,255,.75)',2); label('BESS + PROTECTION CABINET',cx-78,34); break;
  }
  ctx.fillStyle='rgba(216,249,255,.66)';ctx.font='600 10px system-ui';ctx.fillText('CONCEPTUAL 3D · PARAMETRIC VIEW · NOT A CONSTRUCTION DRAWING',12,h-12);
}
function updateControlLabels(){$('nxRotateLabel').textContent=state.rotate?'ON':'OFF';$('nxGridLabel').textContent=state.grid?'ON':'OFF';$('nxRenderState').textContent=state.run?'3D ON':'3D PAUSED';$('nxLive').className='nx-badge '+(state.run?'':'off');$('nxLive').innerHTML=`<i class="led"></i>${state.run?'SIMULATION LIVE':'SIMULATION PAUSED'}`;}
function renderAll(){renderModelGallery();renderInputs();updateControlLabels();calculateCurrent()}
function bind(){
 document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'})));
 $('nxRunToggle')?.addEventListener('click',()=>{state.run=!state.run;saveState();$('nxRunToggle').textContent=state.run?'STOP SIMULATION':'START SIMULATION';updateControlLabels()});
 $('nxRotateToggle')?.addEventListener('click',()=>{state.rotate=!state.rotate;saveState();updateControlLabels()});
 $('nxGridToggle')?.addEventListener('click',()=>{state.grid=!state.grid;saveState();updateControlLabels();draw3D()});
 $('nxReset')?.addEventListener('click',()=>{try{localStorage.removeItem(keyForInput())}catch(_){}renderInputs();calculateCurrent()});
 $('nxAdminLogin')?.addEventListener('click',()=>{let key='IGERS-2026';try{key=localStorage.getItem('igersNextGenAdminKey')||key}catch(_){}const pass=prompt('IGERS local simulation admin key:');if(pass===key){sessionStorage.setItem('igersNextGenAdmin','1');$('nxAdminState').textContent='UNLOCKED';$('nxAdminState').classList.remove('warn');$('nxAdminNote').textContent='Local simulation controls unlocked. Client-side only.';const next=prompt('Set a new local admin key? Leave blank to keep current.');if(next){try{localStorage.setItem('igersNextGenAdminKey',next)}catch(_){}$('nxAdminNote').textContent='Local admin key updated for this browser. Client-side only.'}}else if(pass!==null){$('nxAdminNote').textContent='Local admin key rejected.'}});
 const top=$('nxTop');window.addEventListener('scroll',()=>top?.classList.toggle('show',window.scrollY>600));top?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
 window.addEventListener('resize',draw3D);
}
function tick(){if(state.run){if(state.rotate)angle+=.012*state.intensity;draw3D();}$('nxClock').textContent=nowTime();$('nxHeartbeat').textContent='1.0 s';}
function init(){inject();if(!$('engineeringLab'))return;renderAll();bind();try{if(sessionStorage.getItem('igersNextGenAdmin')==='1'){$('nxAdminState').textContent='UNLOCKED';$('nxAdminState').classList.remove('warn')}}catch(_){}setInterval(tick,1000);requestAnimationFrame(function raf(){if(state.run){if(state.rotate)angle+=.008*state.intensity;draw3D()}requestAnimationFrame(raf)});window.IGERS_NEXTGEN={models,state,recalc:calculateCurrent};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
